pinballmap/pbm

- app/controllers/api/v1/location_machine_xrefs_controller.rb
- app/controllers/api/v1/machine_score_xrefs_controller.rb
- app/controllers/api/v1/machines_controller.rb
- app/controllers/application_controller.rb
This adds support for setting a HTTP status code when the API responds to a request. Fixes issue https://github.com/scottwainstock/pbm/issues/339
> HTTP Status Code In API Response

- app/controllers/api/v1/location_machine_xrefs_controller.rb
- app/models/location_machine_xref.rb
- app/models/machine_comment.rb
- app/models/machine_condition.rb
- db/migrate/20150128151820_create_machine_comments.rb
- db/migrate/20150128155902_rename_machine_comment_to_machine_condition.rb
- db/schema.rb
This creates a new model, Machine Conditions, which stores all conditions about a machine entered. As the condition for a machine_location_xref is updated a new MachineCondition is created.
The only issue I'm having is making these show up in the API responses for the locations API.
> Support for new Machine Conditions model

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/controllers/location_machine_xrefs_controller.rb
- app/controllers/machine_conditions_controller.rb
- app/views/location_machine_xrefs/_update_machine_condition.html.haml
- app/views/locations/_render_machine_conditions.html.haml
- app/views/locations/_render_machines.html.haml
- app/views/machine_conditions/_show_machine_conditions.html.haml
- config/routes.rb
This makes Machine Conditions visible on the site. If you come across any issues let me know and I can fix them.
> Site support for Machine Conditions

- app/controllers/api/v1/locations_controller.rb
This adds support for machine conditions property in the /locations API response.
> Include conditions for location machines API

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/views/location_machine_xrefs/_update_machine_condition.html.haml
- app/views/locations/_render_machine_conditions.html.haml
- app/views/locations/_render_machines.html.haml
- spec/features/location_machine_xrefs_controller_spec.rb
> removed condition delete, and restyled some stuff.

- app/assets/stylesheets/application.css.erb
- app/views/locations/_locations.html.haml
This breaks a test! Actually, I can't really tell if it's a test or a plain ol' ruby error. The error comes from a controller, and is related to adding .empty? to the locations file. I can't figure out how to fix it, though.
> show operator link if available

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mediaqueries.css
- app/views/pages/_header.html.haml
mostly fixed, at least. You have to click something else on the page for the dropdown menus to disappear... oh well.
> fixed dropdown menu on ios tablet

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/views/pages/_header.html.haml
I'm a dumbass, and broke the header menu (though not in a super terrible way) in the previous commit, in mobile non-tablet view. But now it's fixed!
This request also contains a commit and then reversion of a commit. Hopefully that's not a problem.
> fixed header menu in mobile

- app/assets/stylesheets/mobile-application.css.erb
Edited via the github website. They make me commit every time I save a file.
> high score margin on mobile

- app/assets/javascripts/application.js.erb
- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mediaqueries.css
- app/assets/stylesheets/mobile-application.css.erb
- app/views/pages/_header.html.haml
Just added the geo location button to the home page. And if it doesn't work, there's just a window alert. Not sure if windows alerts are janky.
> added geolocation to home page

- app/assets/stylesheets/application.css.erb
- app/views/locations/_render_desc.html.haml
I hope that merge I did doesn't mess anything up in the branch. It seems to be fine on my end, though: issue_385 has the location timestamp stuff, and master doesn't.
> styled location timestamp and restyled location description

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
> Two more minor fixes.

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mediaqueries.css
- app/assets/stylesheets/mobile-application.css.erb
- app/views/pages/_header.html.haml
Not perfect, but it's a start. This menu stuff is tough.
> styled closest locations and rest of menu

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
https://github.com/RyanTG/pbm/issues/110
> minor misc style changes

- app/assets/stylesheets/application.css.erb
- app/views/pages/home.html.haml
One less thing to load. I forgot to remove it in that last commit.
> removed open sans font

- app/views/pages/store.html.haml
> fixed a typo on the store

- app/assets/stylesheets/application.css.erb
- app/views/locations/_render_desc.html.haml
- app/views/locations/_render_update_metadata.html.haml
Just using it in some places so far, where it was a little harder to read the other font.
> added a second monospace font

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/views/layouts/application.html.haml
- app/views/locations/_render_update_metadata.html.haml
Sorry, I didn't do it correctly the first time. This fixes it. 
I also added it to more spots. But this is still a work in progress. It's tedious.
> fixed second font, and added it to more places

- app/assets/stylesheets/application.css.erb
I thought I was done for the night, but I wasn't. But now I am! No prob if you don't deploy this tonight.
> some more font updates

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/views/locations/_form.html.haml
I should probably get out of the habit of also fixing other things in single commits.
> styled flash error message

- app/views/pages/store.html.haml
Removed the text that made it seem like we were making money off the shirts, since we're not.
> removed some text from store

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mediaqueries.css
- app/assets/stylesheets/mobile-application.css.erb
- app/views/locations/_locations.html.haml
- app/views/locations/_render_machines.html.haml
- app/views/pages/_header.html.haml
I added the sign in link to the header and to two places in the location info. In the location info, I made the text bright red for now. This is just temporary... I just wanted it to be super visible.
I didn't add any logic for things like, "if logged in, changed "sign up / log in" to "log out" etc. I didn't know how to do that logic. I know we have things like '- if mobile_device?' but I wasn't sure if we had the same if logged in.
> initial ux for user sign-in

- app/assets/stylesheets/application.css.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.erb
- app/views/locations/_locations.html.haml
- app/views/locations/_render_machines.html.haml
- app/views/pages/_header.html.haml
- app/views/users/registrations/new.html.erb
I didn't finish styling the username box. I didn't understand why it used "textarea" rather than "input"
> some more auth styling

- app/assets/stylesheets/mobile-application.css.erb
- app/views/pages/_header.html.haml
No rush. I just hid the menu on the mobile site behind a hamburger icon.
Not sure if I should merge it to my master before doing a pull request. I guess it's unnecessary. Also, it says I'm behind upstream/master. Hopefully there are no problems. I did a pull beforehand...
> added javascript to mobile menu

- app/assets/stylesheets/application.css.erb
- app/views/locations/_render_update_metadata.html.haml
Oops, I forgot to submit this pull request.
> couple more post-icon css adjustments

- app/assets/stylesheets/application.css.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
This doesn't feel done done. But it's something for now. Once this is merged, maybe I'll try pulling your clean code to see if I get the correct stuff.
> Some auth_required css

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mediaqueries.css
- app/assets/stylesheets/mobile-application.css.erb
Two things I have some trouble with:
1. On the login form, there isn't much space between "Forgot your password?" and "Didn't receive confirmation instructions?" and I can't seem to find where to add that space.
2. The "welcome" text - like the text that says "signed in successfully". That is a div that is always present, but most of the time it doesn't have content in it. If I add a background color, that color shows up all the time even if there isn't any content in the div. So, I'm really limited in how I can style it.
Oh, and right now I'm having trouble signing up a new user. I wanted to see what the "check your email" message looks like on desktop and mobile. But I can't see that message. Can you look at it and tell me if it looks messed up on desktop and/or mobile?
> mobile style for auth

- app/assets/stylesheets/application.css.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/shared/_links.erb
augh, sorry I merged your branch after I committed (but before I pushed).
> more login style

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/views/locations/_render_machines.html.haml
- app/views/locations/_render_update_metadata.html.haml
- app/views/pages/_header.html.haml
Kind of janky, but I started a new branch. I was having trouble pushing on that old one.
> Auth required2

- app/views/devise/registrations/new.html.erb
I added a small note suggesting that people use their initials for their username.
> sign up text

- app/assets/stylesheets/application.css.erb
Sorry, I tried to get this done before you did that last merge.
But before I made this pull request I merged your latest code, and pushed the merge... hopefully that's ok.
> adjusted top margins of containers

- app/views/events/index.html.haml
- app/views/pages/high_rollers.html.haml
Two broken tests related to the event date. It's no displaying event 1 or 5. Obviously, I caused this by changing the date format. But I can't figure out how to fix it. It displayed some of the events but not all...
> formatted event date and high roller date

- app/views/layouts/application.html.haml
Used this solution: http://stackoverflow.com/a/30473228
of completely removing http: or http: from the map api link. So the link just looks like //maps...
Kind of strange, but it seems to work. It makes it so the browser chooses which protocol to use.
sorry about all my flailing. I changed a lot of CSS today, and made some good improvements! But I also flailed.
> Auth required

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/views/devise/sessions/new.html.erb
- app/views/locations/_render_scores.html.haml
- app/views/pages/_header.html.haml
- app/views/pages/donate.html.haml
- app/views/pages/faq.html.haml
- app/views/pages/high_rollers.html.haml
- app/views/pages/store.html.haml
All tests pass!
This was a really long time coming, but I reformatted the high scores (both in the machine details, and on the high rollers page), and I think it looks way better.
> Three commits

- app/assets/stylesheets/application.css.erb
- app/controllers/pages_controller.rb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/events/index.html.haml
- app/views/pages/_header.html.haml
- app/views/pages/profile.html.haml
- config/routes.rb
Profile page template. More info in an issue that I'm about to create.
> styled edit user page; created profile page

- app/assets/stylesheets/application.css.erb
- app/views/locations/_render_last_updated.html.haml
- app/views/pages/_header.html.haml
- app/views/pages/get_a_profile.html.haml
- app/views/users/profile.html.haml
What do you think of the get_a_profile page now? I basically turned it into a TEMPLATE for a profile page. Like, it has the same format, but (for example) the "number of locations edited" = "??"
> style get a profile page

- app/views/pages/store.html.haml
> updated store inventory

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/views/devise/registrations/new.html.erb
- app/views/pages/inspire_profile.html.haml
I want to see what travis says about those two errors I mentioned in email. I don't see why this commit should be breaking these tests.
> minor style tweaks

- config/routes.rb
I'll make this change on auth, too, just to help with merge conflicts in the future.
> changed burlington region to vermont, added redirect from old url

- app/assets/stylesheets/application.css.erb
- app/controllers/pages_controller.rb
- app/helpers/pages_helper.rb
- app/views/layouts/application.html.haml
- app/views/pages/_header.html.haml
- app/views/pages/app.html.haml
- app/views/pages/app_support.html.haml
- app/views/pages/home.html.haml
- app/views/pages/inspire_profile.html.haml
- app/views/pages/privacy.html.haml
- app/views/users/profile.html.haml
- config/initializers/rails_admin.rb
- config/routes.rb
- spec/features/pages_controller_spec.rb
- spec/features/users_spec.rb
- spec/helpers/pages_helper_spec.rb
I think this is fine. It's a really basic edit.
> show username in admin/user

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mediaqueries.css
- app/assets/stylesheets/mobile-application.css.erb
- app/views/pages/_header.html.haml
- app/views/pages/about.html.haml
- config/routes.rb
I just figured that in case people ever type /profile, they'll get redirected to the correct page (to /inspire_profile, which, if logged in, will redirect to their actual profile).
I don't think this will mess anything up.
> direct from /profile to /inspire_profile

- app/models/ability.rb
Can you feel this? Anything else needed?
> only portland admin can edit location type

- app/assets/stylesheets/mobile-application.css.erb
- app/models/ability.rb
- app/views/pages/_header.html.haml
> disallow location type edit for regular admins

- app/assets/stylesheets/application.css.erb
- app/views/layouts/application.html.haml
- app/views/locations/_map.html.haml
- app/views/pages/region.html.haml
1) Tell me what you think
2) I'd like to test this on staging. The map fails to load on some regions, giving an API error. Given that I don't have an api key on dev, I want to see if this error is resolved on staging. If not, the error seems to occur on regions that do not have a MOTD (pretty strange! might just be a coincidence). Anyway, whenever you have a chance, please put it on staging.
> display map on region load

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
I'll do a little more testing on this styling. But it seems gud
> restyled flash messages

- app/assets/stylesheets/application.css.erb
The map issue you noticed on Sunday was also happening on the live site. I think it has to do with a google maps update. I don't think it was on our end.
But here's the fix for the live site.
> fixed weird map overlay issue

- app/assets/javascripts/application.js.erb
- app/views/twincities/region.html.haml
Side note: I have some trouble on the master branch these days - I think because I'm using the same database for master and auth? Like, on some locations on master, I get an error related to "Rank" not being recognized.
Anyway, I tested this and it seems fine.
> fixed infowindow resize bug after machine additions

- app/assets/stylesheets/application.css.erb
and update to the sign-up error text.
> minor adjustment to join container

- app/views/layouts/application.html.haml
The map doesn't load on the https domain (which also prevents the location details from loading). This should fix it.
> use ssl-neutral maps api

- app/assets/robots.txt
- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/helpers/pages_helper.rb
- app/views/layouts/application.html.haml
- config/environments/production.rb
Whoops, forgot to send this PR last night.
> css fix and more

- config/environments/production.rb
> force ssl except api

- app/assets/stylesheets/application.css.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/pages/_header.html.haml
The header still looked a little sloppy for non-admins, now that the admin link is there. But this cleans it up. 
I don't have a non-admin account on dev, though, for full testing. But still, this seems ok.
> moved the 'closest' text to right side on desktop

- app/views/pages/_header.html.haml
- config/initializers/rack_attack.rb
Simplified the header somewhat! It's still a little unwieldy, but I removed like 55 lines.
> moved contact link and sorta refactored header code

- README.md
Sorry, I should have done this before you merged.
> adding one thing to readme

- config/initializers/rack_attack.rb
We'll see if this makes a difference with the spammers hitting the site.
> exponential throttling with rack attack

- README.md
- app/views/machine_score_xrefs/_add_high_score.html.haml
I need to take a closer look at the sort order for high scores. Seems wacky?
> update readme, and clear high score input after submit

- app/models/ability.rb
- app/models/suggested_location.rb
If you're around, can you merge/deploy this? I need to fix some things on live, and this'll help me.
> validate suggested location fields and super admin edit

- app/assets/stylesheets/mobile-application.css.erb
- app/views/pages/_header.html.haml
- app/views/pages/app.html.haml
Mobile header:
1) I made it consistent across region and non-region pages.
2) On the region pages, I was concerned that the header was a little too small (hard to click), so the height is now a little taller.
3) Tucked the "login" links within the menu (to save space).
> Adjusted mobile header, edited app page

- config/routes.rb
sorry, I had this left in there. just the flier page I'm working on. not sure if that's bad to have in the routes at this stage.
> removed flier page

- app/assets/stylesheets/application.css.erb
I was messing with firefox's internal css, and realized that it was affecting the pbm dropdown menu. which means I wasn't explicit enough about some of the styles.
> minor style update to dropdown select

- app/views/locations/_form.html.haml
- db/schema.rb
Remove location from url if other type of search is made
> #818 Update url upon location search.

- .rubocop.yml
- app/assets/stylesheets/application.css.erb
- app/controllers/application_controller.rb
- app/helpers/pages_helper.rb
- app/views/location_machine_xrefs/index.rss.builder
- app/views/locations/_render_update_metadata.html.haml
- config/routes.rb
- spec/controllers/pages_controller_spec.rb
- spec/helpers/pages_helper_spec.rb
- spec/requests/api/v1/locations_controller_spec.rb
Getting this offense on the page title page. Not sure what it means. Too many elements in this module? Do you know how to resolve it?
````
Offenses:
app/helpers/pages_helper.rb:1:1: C: Metrics/ModuleLength: Module has too many lines. [101/100]
module PagesHelper ...
^^^^^^^^^^^^^^^^^^
133 files inspected, 1 offense detected
RuboCop failed!
````
> rss text; bcc; privacy policy page title

- app/assets/stylesheets/application.css.scss.erb
minor, but small improvement until I have time to work on it more.
> minor css change to home page

- app/assets/stylesheets/application.css.scss.erb
- db/schema.rb
p.s. this schema update happened automatically when I did db:migrate last week. I didn't commit it. But now I have. Let me know if I should have stashed it instead.
> replaced palatino font with lato

- app/assets/stylesheets/application.css.scss.erb
- app/views/devise/registrations/new.html.erb
still figuring out GDPR stuff. But I know that this text was not in line with it.
> removed text about mailing list from sign up page

- app/assets/stylesheets/application.css.scss.erb
> styling the number of locations in results text

- README.md
- updated README for new ruby version 2.5.1
- would like a data dump, please!
> update README for ruby 2.5.1

- app/views/location_picture_xrefs/_form.html.haml
- db/schema.rb
> show loading gif while picture is uploading

- Dockerfile
- Gemfile
- Gemfile.lock
Using the Alpine base image for Docker to reduce disk size.
> Dockerize with alpine

- app/assets/stylesheets/application.css.scss.erb
- db/schema.rb
@scottwainstock I can't see the map at all in dev. mapbox key is missing. Do I need to include the token in the `bundle exec rails s` command? And can you verify that this commit doesn't break anything:
- Load http://localhost:3000/portland
- Lookup a location
- See if the map looks ok (doesn't overlap over the results container), and you can zoom and drag it.
> adjusted z index of #map to fix microsoft edge mapbox gl issue

- app/assets/stylesheets/application.css.scss.erb
- app/assets/stylesheets/mediaqueries.css
- app/assets/stylesheets/mobile-application.css.erb
- app/views/pages/_header.html.haml
- app/views/pages/_intro.html.haml
- app/views/pages/_menu.html.haml
- app/views/pages/home.html.haml
- app/views/users/profile.html.haml
- spec/features/users_spec.rb
My local tests are still wack. So I'll check for travvy trav here. 
But I think this is good to go. There's a window alert on the profile page. I didn't remove it.
> media queries and style for fave locations

- app/assets/javascripts/application.js.erb
- app/assets/stylesheets/application.css.scss.erb
- app/assets/stylesheets/mediaqueries.css
- app/assets/stylesheets/mobile-application.css.erb
- app/views/locations/_form.html.haml
- app/views/locations/_map.html.haml
- app/views/pages/_header.html.haml
- db/schema.rb
Hmm, there are a lot of commits in here that I thought I discarded. I mean, I _did_ revert them, so the code from those commits isn't in this PR. But the commits themselves are still there. Strange.
the only code I'm pushing here are CSS things.
> use % on results container width; replace most greys with blue-toned color scheme

- app/models/user.rb
- spec/models/user_spec.rb
This addresses #1133. I have no idea what the best syntax should be to fix this, but the first commit changes a test to show the bug exists and the commit fixes it from what I can tell.
> High score bug

- app/assets/stylesheets/application.css.scss.erb
> login button color

- app/controllers/api/v1/regions_controller.rb
- spec/requests/api/v1/regions_controller_spec.rb
> Do not require auth to send message via API. Update tests accordingly.

- app/views/pages/map.html.haml
- config/environments/production.rb
I think force_ssl was accidentally commented out.
> uncomment force_ssl; check the redo checkbox on /map when results load

- app/models/location.rb
- config/environments/production.rb
I can't test this on local. Hopefully it works.
> exclude subdomains in ssl_options

- .env.local.example
- .envrc
- .gitignore
- Dockerfile
- README.md
- docker-compose.postgres.yml
- docker-compose.yml
Picks up https://github.com/scottwainstock/pbm/issues/1024
* Updates Dockerfile to support updated Ruby version and removes unnecessary layers
* Modifies `docker-compose.yml` to support a fully containerized pinballmaps app. 
* Contains a "setup" container to seed the database if first run or if starting fresh
* Docker Volume for persistence if needed
* Adds a postgres-only compose file.
* Allows you to run containerized postgres, but run rails commands locally and modify code without having to restart containers or deal with file write lags.
* Updates README with Docker usage and version change
* Adds direnv (or other environment variable usage) support
README contains all the necessary info for getting either docker use case running.  Feel free to nix any part of the additions in here …
> Dockerize app

- app/views/pages/home.html.haml
This is my first ever PR to any repo :)
> Fix misspelling of 'heatmap' on home page

- config/initializers/rails_admin.rb
- db/migrate/20210413230424_add_icon_to_location_type.rb
- db/schema.rb
> add icon and library fields to location types

- app/assets/stylesheets/application.css.scss.erb
- app/views/pages/home.html.haml
- spec/features/pages_controller_spec.rb
- spec/spec_helper.rb
Don't show # of locations/machines anymore (for faster loading and a simpler look).
> simplify list of regions on home page

- app/controllers/application_controller.rb
- spec/controllers/pages_controller_spec.rb
- spec/requests/api/v1/locations_controller_spec.rb
> Adjust the admin suggest location text some more

- app/assets/stylesheets/application.css.scss.erb
Why did I hide that down arrow in the first place?
> Adjusting button radius; and making down arrow show on selects

- app/controllers/api/v1/locations_controller.rb
- spec/requests/api/v1/locations_controller_spec.rb
> Some adjustments to no_details api flag

- app/controllers/api/v1/locations_controller.rb
fuggin whoops. Accidentally included something that I was just testing. I don't think it affected anything.
> Oops, removing an except that I did not mean to include

- app/controllers/pages_controller.rb
- app/models/machine.rb
- app/views/locations/_render_update_metadata.html.haml
- app/views/rails_admin/main/_operator_select.html.haml
- spec/spec_helper.rb
Even if the operators don't belong to that region.
Allow admins to tag locations with any operator.
> Show all Operators tagged at locations in regional search

- app/controllers/api/v1/operators_controller.rb
> Exclude created_at and updated_at from operator endpoints

- app/assets/stylesheets/application.css.scss.erb
- app/models/user.rb
At first I didn't like mapper, but now I like it.
> Change rank title from contributor to mapper

- app/models/user.rb
> Fixed ranking criteria

- app/controllers/api/v1/location_machine_xrefs_controller.rb
> use alias on manufacturer in top 4 machines endpoint

- app/controllers/api/v1/user_submissions_controller.rb
- spec/requests/api/v1/user_submissions_controller_spec.rb
Earlier submissions weren't formatted correctly.
> Added date limitation to user_submission location endpoint

- app/controllers/api/v1/locations_controller.rb
- app/controllers/api/v1/user_submissions_controller.rb
- config/environments/production.rb
- config/initializers/apipie.rb
- config/routes.rb
- spec/requests/api/v1/locations_controller_spec.rb
- spec/requests/api/v1/user_submissions_controller_spec.rb
Made tests, but put some in separate commits. Not good practice, but I wanted to wait to do the tests until the end.
> More API endpoints for app stats page

- app/controllers/api/v1/locations_controller.rb
- app/controllers/application_controller.rb
- spec/requests/api/v1/locations_controller_spec.rb
This is still over the cyclomatic complexity threshold, but it's an improvement.
> Improve rubocop results

- render.yaml
So will manually add some crons
> hit the render.yaml service limit

- app/views/pages/suggest_new_location.html.haml
- config/routes.rb
This seems suspiciously easy. I hope it fixes the 502 gateway issue!
> change submitted location from get to post

- app/views/layouts/application.html.haml
- app/views/pages/suggest_new_location.html.haml
Previously we were using Scott's gmaps api key for the website and mine for the app. But for this change, we had to enable the Places API and the Javascript API. Unclear if those were already enabled on Scott's - so instead I just switched the environment variable to my key.
> Use Google Place API on location submission form

- db/seeds.rb
fixes a column name in the seeds file.
> update seeds.rb link => external_link

- .vscode/launch.json
- Gemfile
- Gemfile.lock
- README.md
- bin/debug
run bin/debug and then attach to the running port in vscode
> Add vscode debugging support out of the box

- README.md
also, use bin/{rails|rake} for most tasks since the binstubs are the recommended way.
> Cleanup the MacOS setup documentation

- .solargraph.yml
- Gemfile
- Gemfile.lock
adds solargraph rails as a plugin
> add a solargraph config file

- app/controllers/api/v1/location_machine_xrefs_controller.rb
- spec/requests/api/v1/location_machine_xrefs_controller_spec.rb
Changes the param name for the nested resource and remove erroneous test data
> Fixup the lmx api

- app/views/locations/_locations.html.haml
- app/views/locations/_render_last_updated.html.haml
- app/views/locations/_render_machine_conditions.html.haml
- app/views/locations/_render_scores.html.haml
ran into a couple of these while testing locally, this will make it match whatever the app is currently running as
> use request.scheme instead of hardcoded https

- app/controllers/api/v1/locations_controller.rb
Probably should refactor it a bit more
> Tidies up the long line a little bit.

- app/controllers/api/v1/location_machine_xrefs_controller.rb
- config/routes.rb
- spec/requests/api/v1/location_machine_xrefs_controller_spec.rb
We can use this to return the most recent N machines added within N miles
> Add /api/v1/location_machine_xrefs/most_recent_by_lat_lon.json

- app/controllers/machine_conditions_controller.rb
- app/models/machine_condition.rb
- spec/controllers/machine_conditions_controller_spec.rb
- spec/models/machine_condition_spec.rb
Addressed comments here: https://github.com/pinballmap/pbm/pull/1577
Added blank/dupe machine condition checks.
> Update/delete machine conditions: code review updates

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/layouts/application.html.haml
- spec/features/pages_controller_spec.rb
helps for discord previews
closes #1575
> Add preview title to direct links to locations

- app/controllers/machines_controller.rb
When searching for machines use the speed of the database to select exactly what we want for autocomplete results.
cleaned up the other if branch for readability
> Make the region machine search faster

- app/views/layouts/application.html.haml
when using a controller not inherited by ApplicationController @title_params could be nil. (devise for one and maybe others)
> fixes nil error

- Gemfile
- Gemfile.lock
- config/environments/test.rb
- spec/features/location_machine_conditions_cache_spec.rb
- spec/features/location_machine_xrefs_controller_spec.rb
- spec/features/locations_controller_spec.rb
- spec/features/machine_score_xrefs_controller_spec.rb
- spec/features/pages_controller_spec.rb
- spec/features/users_spec.rb
- spec/spec_helper.rb
removes rack_session_access gem and uses devise helpers to login
> Remove rack_session_access gem

- README.md
- Rakefile
adds a rake task to create a default admin user in development to get up and running easier
> Add Dev admin user rake task
