- app/assets/stylesheets/application.css.erb
I finally figured out why the white space (like line breaks) from textareas weren't preserved after you hit "save"! (if you edited an existing comment, the white space in that comment would magically return - indicating that there was something in the machine comment span that was styling the white space).
This will really help with machine comment readability on the website.
> preserve white space in machine comments

- app/controllers/location_machine_xrefs_controller.rb
- app/models/location_machine_xref.rb
- app/views/location_machine_xrefs/_update_machine_condition.html.haml
- app/views/locations/_render_machine_conditions.html.haml
- app/views/machine_conditions/_show_machine_conditions.html.haml
Fixes following issues:
- Remove old condition when editing machine condition
- Refresh the visibility of the "Show Past Conditions" when needed, such as after no more past conditions exist or after the second condition is added. NOTE: If a machine has no past conditions and you add one the "Show Past Conditions" section will not appear since that is the latest condition. Once you add a second condition then the "Show Past Conditions" section will appear with the previous condition visible.
- No longer show the current condition in past conditions section
> Machine Condition Site Improvements

- app/controllers/pages_controller.rb
- app/models/event.rb
- app/models/region.rb
- db/migrate/20151102053730_add_indexes.rb
- db/schema.rb
- spec/models/machine_spec.rb
- spec/models/region_spec.rb
This PR adds indexes for foreign keys and addresses #414. This should hopefully improve site performance a bit.
A couple of notes. Since we're adding an index that is commonly used for scopes (i.e., the `region_id` index in `locations` table), Postgres changes the sort order a bit. I.e., when you run `SELECT * FROM locations WHERE region_id = 1`, Postgres was returning rows in _descending_ order based on `location_id` since it was using the btree index on `region_id`. As a result, we have either two options:
+ Sprinkle in a bunch of `order` clauses on associations. (i.e., `has_many :users, -> { order 'users.id' }`)
+ Do not rely on default sorting order unless necessary. (I.e., specify `order('users.id')` within application logic).
I kind of prefer the last one, but those changes would …
> Add db indexes

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mediaqueries.css
- app/assets/stylesheets/mobile-application.css.erb
- app/views/pages/region.html.haml
- spec/features/pages_controller_spec.rb
Pretty simple style update. Just widened the entire results section. Also, removed the high score ticker. May add it back, but for now it's gone. 
To make that test pass, I simply removed the two tests where it looks for a ticker.
> widened lookup and results container to 600px, removed high score ticker

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
Hopefully this isn't too brutish to say "display: none" for these two divs. But I don't see them reused anywhere. The meta info alert uses a different div ID.
> location submission message was showing up twice

- app/assets/stylesheets/application.css.erb
- app/views/locations/_render_desc.html.haml
- app/views/locations/_render_last_updated.html.haml
My edits to app/views/locations/_render_desc.html.haml seem really inelegant.
The goals:
1) show the location update date for logged out users (but not the update icon). But there's an if statement around the entire thing. I tried to put "if logged in || if not logged in" within that first if statement, and that didn't work. So instead, I moved the first if statement down one line, so the opening div is outside of it. Further below, I hid the update icon with another if statement. But again, I had to put it one line below the opening icon div (line 14). If I put it before that confirm_location_button div, then the update message wouldn't show up for logged out users.
2) in the "by username" text, I only wanted the username to be a different color/font. So I made two "if logged in" …
> styled username, and display update date for all users

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mediaqueries.css
- app/assets/stylesheets/mobile-application.css.erb
- app/views/layouts/application.html.haml
- app/views/pages/_header.html.haml
Lotta header changes here (mostly on mobile). Tell me how you think it looks/works. I tested it with lots of different devices (emulations), and it seems good/functional. The overall idea is a small fixed header that is always present on the screen and contains the menu link and the login/out links. I smooshed the pbm logo in there.
On the home page, the header contains a full width pbm logo, and the menu items below it. Both lines are fixed.
I don't think this takes up too much screen real estate. And this seems like common practice - lots of websites do it these days (though the menu isn't always fixed. github is an example of a non-fixed version; lyft is an example of a fixed version).
Only outstanding issue is the flash message stays on the screen forever unless you go to another …
> on mobile, fixed and more compact header, other minor header styles

- app/assets/stylesheets/application.css.erb
- app/assets/stylesheets/mobile-application.css.erb
- app/views/locations/_render_desc.html.haml
- app/views/locations/_render_update_metadata.html.haml
- spec/features/location_machine_xrefs_controller_spec.rb
- spec/features/locations_controller_spec.rb
Not too happy with the tests.
This `find('#location_detail_location_#{@location.id} .location_meta .meta_image').click` produces a fail, while this `find('.location_meta span.meta_image').click` does not. 
But using `#location_detail_location_#{@location.id}` in the selector works fine for descriptions. I don't get why it doesn't work for the meta span. The error is: 
`The browser raised a syntax error while trying to evaluate css selector "#location_detail_location_\#{@location.id} .location_meta .meta_image"`
> fixed a javascript mistake for editing meta and description

- app/assets/stylesheets/mobile-application.css.erb
barely had to change anything. This map-loading looks good on mobile, because previously the intro text used the map div, and I had to size that map div for the map and not for the text. So there was empty space below the text, because the div was too tall.
> mobile style adjustment for region intro text

- app/models/user.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
- config/locales/devise.en.yml
I think this is fine. I removed the "inactive" message that you added in this commit https://github.com/scottwainstock/pbm/commit/1474eb237dbb530bf041c8d53104a01bb8eda0fd
and moved it to here https://github.com/RyanTG/pbm/commit/33466072830c9c2fcfd88cdf3383c78bec7d8a9e#diff-f3d6e5d1f2709fef60571f46916a5f23
If I disable an account, and then try to log in with the account, I see that message. So it seems like it's working.
> moved alert for disabled users to devise locale; updated the confirm message

- app/assets/stylesheets/application.css.erb
- app/controllers/api/v1/locations_controller.rb
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/pages/suggest_new_location.html.haml
- spec/controllers/pages_controller_spec.rb
- spec/requests/api/v1/locations_controller_spec.rb
Added fields to submit location form and associated tests. Confirmed fields from form are populating in the user_submissions table. Pulled location_types from db model... set default to "Bar" rather than the alphabetical selection of "Adult Shop" :) 
With regard to the form appearance itself, had to use breaks to get the textareas to format nicely. I'm sure there's likely a more elegant way?
Thank you for the help and patience as I've been getting to know this project!
> Additional fields for submit location form

- config/initializers/rack_attack.rb
This is hard to estimate, given that I don't know how many requests occur when, say, adding a machine to a location.
But I added two, and got blocked on the third one! And I'm still blocked, minutes later. At least we know it works.
> doubled the amount of rack requests

- app/controllers/application_controller.rb
- app/models/location.rb
- spec/controllers/pages_controller_spec.rb
- spec/requests/api/v1/regions_controller_spec.rb
Basically reverting one of the commits from last week. Though I didn't remove the def for it. Not sure if that's bad practice.
> allow admin to manually geocode location edits

- app/assets/stylesheets/mobile-application.css.erb
Strangely, the menu icon looked fine on desktop (emulating mobile), but was messed up on an actual mobile device. This fixes it (but makes it look messed up in the emulated version...).
> minor adjustment to mobile header

- app/models/region.rb
- spec/models/region_spec.rb
Perhaps this will fix the Weekly Digests. I noticed that the syntax on https://github.com/scottwainstock/pbm/blob/97fd5a7407139137dcf5881db6d37e75d7dde7e0/app/models/region.rb was displaying weirdly right after it said "Here's" which perhaps was breaking the Weekly Digest stuff below it. So I changed those to "Here is".
> removed some parentheses from daily digests

- app/views/pages/about.html.haml
My postgresql upgraded, and I haven't upgraded the database yet. So I didn't verify that this works on my local. But it's a very simple commit and should be fine!
> remove portland admin link on about page

- app/views/location_machine_xrefs/index.rss.builder
right now the logic is like, "if the RSS feed link is for a region, then the rss item links will include that region. If not, then they'll all use /regionless. But it would be cool if the logic was, "if RSS item is for a location that's within a region, then show that region in url." 
Does that make sense? I can't figure out how to do that.
> include regionless link for the global rss feed

- app/controllers/api/v1/locations_controller.rb
- spec/requests/api/v1/locations_controller_spec.rb
#1147 is returning null if no results come back from autocomplete_city. It is easier to deal with an empty array coming back in the app. 
Looking at the documentation for `uniq!` vs `uniq`, `uniq` seems more appropriate for our needs as it returns an array if no results as well as no duplicates are found.
> Return emtpy array if no results from autocomplete_city

- app/controllers/api/v1/locations_controller.rb
- spec/requests/api/v1/locations_controller_spec.rb
#1151 
Not 100% sure this is totally right, but the new test is passing where the email is being sent to super admins. Kept zone included rather than trying to futz with the controller.
> Remove requirement of region or lat/lon to be present to suggest location

- app/controllers/registrations_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/pages/store.html.haml
This seems to work. But it could use your review.
And I tried to make a test for it, but couldn't get it to function right (although _one time_ it mysteriously passed).
My attempt (not committed):
````
require 'spec_helper'
describe RegistrationsController, type: :controller do
describe 'create' do
it 'should flash an error message if captcha fails' do
expect(controller).to receive(:verify_recaptcha).and_return(nil)
post 'create', params: { username: 'wizard', email: 'pinballwizard@foo.com', password: 'okokok', password_confirmation: 'okokok' }
expect(request.flash[:alert]).to eq('Your captcha entering skills have failed you. Please go back and try again.')
end
end
end
````
error: 
````
1) RegistrationsController create should flash an error message if captcha fails
Failure/Error: …
```
> add recaptcha to devise signup

- app/controllers/api/v1/locations_controller.rb
- spec/requests/api/v1/locations_controller_spec.rb
@scottwainstock This is my first attempt at modifying the API. Tests pass, and I added a new test for this. But let me know if you see any red flags.
The app uses this endpoint to get locations on the map screen. My goal was to add a no_details flag to remove any locations fields that we aren't using on this screen - and then I want to see if this speeds up the app at all. I think the speed improvements would be small - but anything helps, I guess.
Sample endpoint:
http://localhost:3000/api/v1/locations/closest_by_lat_lon.json?lat=45.52819783271801;lon=-122.66291722170914;send_all_within_distance=10;no_details=1
> no details flag for closest_by_lat_lon endpoint, for app

- app/assets/javascripts/application.js.erb
- app/controllers/api/v1/machines_controller.rb
- app/controllers/application_controller.rb
- app/controllers/location_machine_xrefs_controller.rb
- app/views/pages/faq.html.haml
- spec/features/location_machine_xrefs_controller_spec.rb
- spec/requests/api/v1/machines_controller_spec.rb
Machines admins still get notified by email.
Flash messages states that the edit is moderated.
Couldn't get rails flash to work, but instead used js...
> Remove ability of users to add new machine names

- app/assets/stylesheets/application.css.scss.erb
- app/views/locations/_render_update_metadata.html.haml
- spec/features/location_machine_xrefs_controller_spec.rb
I attempted to also put it near the machine comment input box. But I don't think l.operator is available there.
> Display if operator does or does not receive machine comments in location metadata

- app/assets/stylesheets/application.css.scss.erb
- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- app/views/users/profile.html.haml
Ok, this seems better. Does not appear to have N+1 issues, or take longer to load the profile page or the profile_info.json.
Difference this time is that I separated out the admin_rank calculations from the contributor_rank calculations, and used CASE as much as possible.
> Use Case to get user rank and admin title, show on profile page

- Gemfile.lock
- README.md
The new travis account is currently not working because we've "exceeded the number of users" on this account (the number of users in unlimited, so this error doesn't make sense). But at least the badge is updated.
> update readme with new travis account

- app/controllers/api/v1/locations_controller.rb
- app/controllers/application_controller.rb
- spec/requests/api/v1/locations_controller_spec.rb
I did this by:
- in the API, do not use user location for finding nearest region.
- In the application controller, move the geocoding up, and first use geocoded lat/lon to determine region, and if that is not available then fall back to user lat/lon
This functions on the app/api submissions as well as the regionless suggest form. I did not touch the contact form.
The API test feels like a copout, because I don't think we can geocode in Test. So I changed the test to "Does not search boundary boxes by transmitted lat/lon (but instead geocodes)" Not very cool, but I'm not sure what else to do.
> Use geocoded lat/lon of suggested location to determine region

- app/controllers/api/v1/locations_controller.rb
- app/controllers/api/v1/user_submissions_controller.rb
- spec/requests/api/v1/locations_controller_spec.rb
This sets a limit to max_distance of 500 if not using "no_details" and 800 miles if using it. As usual, if not using max_distance, it defaults to the default. This commit is an attempt to set some limits on these endpoints. These may be adjusted in the future.
> Set max_distance max limits

- app/controllers/api/v1/location_machine_xrefs_controller.rb
- config/routes.rb
- spec/requests/api/v1/location_machine_xrefs_controller_spec.rb
Adds a new route `/api/v1/location_machine_xrefs/:id/ic_toggle` that will toggle the insider connected flag for a machine at a location.
Handles updating the location to reflect when a machine has one or more insider connected machines enabled. Will also set the status back to false when there are no more insider connected machines enabled.
Closes  bug #1328
> Add insider connected API to toggle status

- .vscode/launch.json
Increases the timeout to a more reasonable time before attaching to the debugger
Also adds a "Run single test" option which lets you only run and debug the test that is under the currently selected line.
> Change timeout to allow the debug server to start

- .rubocop.yml
not sure if you want to run the new and unconfigured cops but they are not being run right now and just provide errors
> Fix rubocop rule indention and supress warnings

- app/controllers/api/v1/location_machine_xrefs_controller.rb
- app/models/location_machine_xref.rb
- spec/requests/api/v1/location_machine_xrefs_controller_spec.rb
enables the use of:
/api/v1/location_machine_xref/:lmx_id/ic_enabled.json { ic_enabled: "true" }
adds a bang version of the create_ic_user_submssion that raises an exception for the transaction to work properly
> Add an option ic_enabled parameter to the api

- app/views/pages/map.html.haml
- app/views/pages/region.html.haml
the "Redo results when map is moved?" text should be a clickable and this change fixes that.
> Make checkbox label clickable

- bin/debug
Makes it always attach to the right process when debugging.
> Single worker debugging

- db/migrate/20240817222440_add_fast_search_indexes.rb
autocomplete does not constrain search to the start of the string so a trigram index will increase the speed of most autocomplete searches.
> add trigram indexes for autocomplete

- .env.test.local.example
- .gitignore
- .vscode/launch.json
- spec/spec_helper.rb
make chrome testing more configurable and easier to test while debugging.
> Headless chrome tweaks

- app/views/maps/map.html.haml
- Populate hidden form fields with URL parameters on page load
- Initialize JavaScript form state from URL parameters
- Show exact version toggle and clear button when appropriate
- Maintains machine search filters when refresh button is clicked
Fixes #1630
> Fix search parameter persistence in map refresh functionality
